(function(){
  "use strict";
  const config=window.WILD_CONFIG||{},storageKey="wild_referral_coupons_v1",form=document.querySelector("#coupon-form"),result=document.querySelector("#coupon-result"),inviteView=document.querySelector("#invite-view"),formMessage=document.querySelector("#form-message"),submitButton=document.querySelector("#generate-button"),termsDialog=document.querySelector("#terms-dialog");
  const cleanText=(value,max=60)=>String(value||"").trim().replace(/\s+/g," ").slice(0,max),cleanPhone=value=>String(value||"").replace(/[^+\d\s()-]/g,"").trim().slice(0,24),validName=value=>cleanText(value).length>=2,validPhone=value=>String(value||"").replace(/\D/g,"").length>=9,codeIsValid=value=>/^WILD-[A-Z0-9]{6}$/.test(String(value||""));
  function createCode(){const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",bytes=new Uint8Array(6);crypto.getRandomValues(bytes);return `WILD-${Array.from(bytes,byte=>alphabet[byte%alphabet.length]).join("")}`}
  function readLocalCoupons(){try{return JSON.parse(localStorage.getItem(storageKey))||[]}catch(_){return[]}}
  function saveLocalCoupon(coupon){const coupons=readLocalCoupons();coupons.unshift(coupon);localStorage.setItem(storageKey,JSON.stringify(coupons.slice(0,100)))}
  function setFieldError(id,message){const input=document.getElementById(id),error=document.querySelector(`[data-error-for="${id}"]`);if(input)input.setAttribute("aria-invalid",message?"true":"false");if(error)error.textContent=message}
  function validateForm(data){let valid=true;setFieldError("client-name","");setFieldError("client-phone","");setFieldError("friend-name","");formMessage.textContent="";if(!validName(data.clientName)){setFieldError("client-name","Escreve o teu nome.");valid=false}if(!validPhone(data.clientPhone)){setFieldError("client-phone","Escreve um contacto válido.");valid=false}if(!validName(data.friendName)){setFieldError("friend-name","Escreve o nome do teu amigo.");valid=false}if(!document.querySelector("#terms").checked){formMessage.textContent="Tens de aceitar as condições para criar o cupão.";valid=false}return valid}
  async function createCoupon(data){if(config.supabaseUrl&&config.supabaseAnonKey){const response=await fetch(`${config.supabaseUrl}/functions/v1/criar-cupao`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${config.supabaseAnonKey}`,apikey:config.supabaseAnonKey},body:JSON.stringify(data)});if(!response.ok)throw new Error("Não foi possível criar o cupão. Tenta novamente.");return response.json()}const coupon={...data,code:createCode(),status:"pending",createdAt:new Date().toISOString(),demo:true};saveLocalCoupon(coupon);return coupon}
  function inviteUrl(coupon){const base=String(config.siteUrl||location.origin).replace(/\/$/,""),params=new URLSearchParams({codigo:coupon.code,de:coupon.clientName});return `${base}/amigo.html?${params.toString()}`}
  function showCoupon(coupon){document.querySelector("#coupon-client").textContent=coupon.clientName;document.querySelector("#coupon-friend").textContent=coupon.friendName;document.querySelector("#coupon-code").textContent=coupon.code;document.querySelector("#coupon-state").textContent=coupon.status==="active"?"ATIVO":"PENDENTE";const url=inviteUrl(coupon),message=`🔥 ${coupon.friendName}, foste convidado para a WILD Tattoo!\n\nUsa o código *${coupon.code}* quando pedires o teu orçamento. Quando concluíres a tua tattoo, eu ganho uma tattoo grátis até 10 cm. 🖤\n\nVê o convite: ${url}`;document.querySelector("#whatsapp-share").href=`https://wa.me/?text=${encodeURIComponent(message)}`;document.querySelector("#copy-link").dataset.url=url;result.hidden=false;result.scrollIntoView({behavior:"smooth",block:"start"})}
  async function onSubmit(event){event.preventDefault();const formData=new FormData(form),data={clientName:cleanText(formData.get("clientName")),clientPhone:cleanPhone(formData.get("clientPhone")),friendName:cleanText(formData.get("friendName"))};if(!validateForm(data))return;submitButton.disabled=true;submitButton.textContent="A gerar o cupão…";try{showCoupon(await createCoupon(data))}catch(error){formMessage.textContent=error.message||"Ocorreu um erro. Tenta novamente."}finally{submitButton.disabled=false;submitButton.innerHTML="Gerar o meu cupão <span>→</span>"}}
  function showInviteFromUrl(){const params=new URLSearchParams(location.search),code=String(params.get("codigo")||"").toUpperCase();if(!codeIsValid(code))return;const from=cleanText(params.get("de")||"Alguém",40);document.querySelector("#invite-name").textContent=from;document.querySelector("#invite-code").textContent=code;const text=`Olá WILD! Recebi um convite com o código ${code} e quero pedir um orçamento para uma tatuagem.`;document.querySelector("#book-whatsapp").href=`https://wa.me/${config.whatsappNumber}?text=${encodeURIComponent(text)}`;inviteView.hidden=false;document.querySelector(".hero").hidden=true;document.querySelector(".how-it-works").hidden=true;document.querySelector(".creator").hidden=true}
  function renderStatus(coupon){const states={pending:{badge:"PENDENTE",title:"À ESPERA DO AMIGO",description:"O amigo ainda precisa de concluir a tatuagem paga para desbloquear a oferta."},active:{badge:"DESBLOQUEADO",title:"A TUA OFERTA ESTÁ ATIVA",description:"Já podes contactar a WILD para marcar a tua tatuagem grátis até 10 cm."},redeemed:{badge:"UTILIZADO",title:"OFERTA JÁ UTILIZADA",description:"A tatuagem grátis associada a este cupão já foi realizada."}},state=states[coupon.status]||states.pending,card=document.querySelector("#status-result");document.querySelector("#status-code-output").textContent=coupon.code;document.querySelector("#status-badge").textContent=state.badge;document.querySelector("#status-result-title").textContent=state.title;document.querySelector("#status-description").textContent=state.description;card.dataset.status=coupon.status;card.hidden=false}
  async function lookupStatus(code){if(!config.supabaseUrl||!config.supabaseAnonKey){const coupon=readLocalCoupons().find(item=>item.code===code);if(!coupon)throw new Error("Cupão não encontrado.");return coupon}const response=await fetch(`${config.supabaseUrl}/functions/v1/consultar-cupao`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${config.supabaseAnonKey}`,apikey:config.supabaseAnonKey},body:JSON.stringify({code})}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"Não foi possível consultar o cupão.");return payload}
  async function onStatusSubmit(event){event.preventDefault();const input=document.querySelector("#status-code-input"),button=document.querySelector("#status-button"),message=document.querySelector("#status-message"),card=document.querySelector("#status-result"),code=String(input.value||"").trim().toUpperCase();message.textContent="";card.hidden=true;if(!codeIsValid(code)){message.textContent="Escreve um código válido, por exemplo WILD-6NLPWC.";return}button.disabled=true;button.textContent="A pesquisar…";try{renderStatus(await lookupStatus(code))}catch(error){message.textContent=error.message}finally{button.disabled=false;button.innerHTML="Pesquisar código <span>→</span>"}}
  form.addEventListener("submit",onSubmit);document.querySelector("#status-form").addEventListener("submit",onStatusSubmit);document.querySelector("#status-code-input").addEventListener("input",event=>{event.target.value=event.target.value.toUpperCase()});document.querySelector("#copy-link").addEventListener("click",async event=>{try{await navigator.clipboard.writeText(event.currentTarget.dataset.url||location.href);document.querySelector("#copy-status").textContent="Link copiado! Já podes enviá-lo ao teu amigo."}catch(_){document.querySelector("#copy-status").textContent="Não foi possível copiar. Usa o botão do WhatsApp."}});document.querySelectorAll("[data-open-terms]").forEach(button=>button.addEventListener("click",()=>termsDialog.showModal()));document.querySelectorAll("[data-close-terms]").forEach(button=>button.addEventListener("click",()=>termsDialog.close()));termsDialog.addEventListener("click",event=>{if(event.target===termsDialog)termsDialog.close()});showInviteFromUrl();
}());
